import { useState } from "react";
import { useListReports, useGetReportsSummary } from "@workspace/api-client-react";
import { GHS, pct, BRANCHES } from "@/lib/format";
import { FileText, Table2, X, CheckCircle2, Download, Building2 } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";
import { motion, AnimatePresence } from "framer-motion";

const PERIODS = ["Today", "This Week", "This Month", "This Year"];
const BRANCH_FILTERS = ["All", ...BRANCHES];

type ExportType = "pdf" | "excel" | null;

/* ── PDF Document Preview ── */
function PdfPreview({ totals, filtered, period, branchFilter }: { totals: any; filtered: any[]; period: string; branchFilter: string }) {
  const companyName = localStorage.getItem("bc_company") || "BranchControl";
  const today = new Date().toLocaleDateString("en-GH", { year: "numeric", month: "long", day: "numeric" });
  return (
    <div className="bg-white text-[#111] rounded-xl border border-gray-200 shadow-inner overflow-hidden text-[11px]">
      {/* Header bar */}
      <div className="bg-[#0f172a] px-5 py-4 flex items-center justify-between">
        <div>
          <p className="text-white font-black text-sm">{companyName}</p>
          <p className="text-white/50 text-[10px] mt-0.5">Sales Report · {period}</p>
        </div>
        <div className="text-right">
          <p className="text-white/70 text-[10px]">{today}</p>
          <p className="text-white/50 text-[10px]">{branchFilter === "All" ? "All Branches" : branchFilter}</p>
        </div>
      </div>

      {/* Summary row */}
      <div className="grid grid-cols-5 border-b border-gray-100">
        {[
          { label: "Total Sales", value: GHS(totals.totalSales),  color: "#111" },
          { label: "Net Profit",  value: GHS(totals.totalProfit), color: "#059669" },
          { label: "Cash",        value: GHS(totals.totalCash),   color: "#2563eb" },
          { label: "Bank",        value: GHS(totals.totalBank),   color: "#4f46e5" },
          { label: "Credit",      value: GHS(totals.totalCredit), color: "#dc2626" },
        ].map(({ label, value, color }) => (
          <div key={label} className="px-4 py-3 border-r border-gray-100 last:border-r-0">
            <p className="text-gray-400 text-[9px] uppercase tracking-widest font-bold">{label}</p>
            <p className="font-black text-xs mt-0.5" style={{ color }}>{value}</p>
          </div>
        ))}
      </div>

      {/* Table */}
      <div className="overflow-auto max-h-48">
        {filtered.length === 0 ? (
          <p className="text-center text-gray-400 py-6">No reports for this period.</p>
        ) : (
          <table className="w-full">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-100">
                {["Branch", "Date", "Total", "Cash", "MoMo", "Bank", "Credit", "Profit", "Margin"].map(h => (
                  <th key={h} className="px-3 py-2 text-left text-[9px] font-black uppercase tracking-widest text-gray-400">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.map((r, i) => (
                <tr key={r.id} className={i % 2 === 0 ? "bg-white" : "bg-gray-50/60"}>
                  <td className="px-3 py-2 font-bold">{r.branch}</td>
                  <td className="px-3 py-2 text-gray-500">{r.date}</td>
                  <td className="px-3 py-2 font-black">{GHS(r.total)}</td>
                  <td className="px-3 py-2 text-[#059669] font-bold">{GHS(r.cash)}</td>
                  <td className="px-3 py-2 text-[#2563eb] font-bold">{GHS(r.momo)}</td>
                  <td className="px-3 py-2 text-[#4f46e5] font-bold">{GHS(r.bank)}</td>
                  <td className="px-3 py-2 text-[#dc2626] font-bold">{GHS(r.credit)}</td>
                  <td className="px-3 py-2 text-[#7c3aed] font-bold">{GHS(r.profit)}</td>
                  <td className="px-3 py-2 text-gray-500">{pct(r.profit, r.total)}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Footer */}
      <div className="px-5 py-2.5 border-t border-gray-100 bg-gray-50 flex justify-between items-center">
        <p className="text-gray-300 text-[9px]">Generated by BranchControl · ChalePay</p>
        <p className="text-gray-300 text-[9px]">Page 1 of 1</p>
      </div>
    </div>
  );
}

/* ── Excel Spreadsheet Preview ── */
function ExcelPreview({ totals, filtered, period, branchFilter }: { totals: any; filtered: any[]; period: string; branchFilter: string }) {
  const cols = ["Branch", "Date", "Status", "Total", "Cash", "MoMo", "Bank", "Credit", "Profit", "Margin"];
  return (
    <div className="rounded-xl border border-gray-200 overflow-hidden text-[10px] bg-white">
      {/* Toolbar strip */}
      <div className="bg-[#1d6f42] px-4 py-2 flex items-center gap-2">
        <Table2 className="h-3.5 w-3.5 text-white/80" />
        <span className="text-white font-bold text-[11px]">BranchControl_Report_{period.replace(/\s+/g, "_")}.xlsx</span>
      </div>

      {/* Sheet tab */}
      <div className="flex bg-gray-100 border-b border-gray-200 px-2 pt-1.5 gap-1">
        <div className="bg-white border border-gray-200 border-b-0 rounded-t px-3 py-1 text-[10px] font-black text-[#1d6f42]">Summary</div>
        <div className="bg-gray-50 border border-gray-200 border-b-0 rounded-t px-3 py-1 text-[10px] text-gray-400">By Branch</div>
      </div>

      {/* Summary kpis */}
      <div className="grid grid-cols-5 border-b border-gray-200 bg-[#e8f4f0]/60">
        {[
          { label: "TOTAL SALES", value: GHS(totals.totalSales) },
          { label: "NET PROFIT",  value: GHS(totals.totalProfit) },
          { label: "CASH",        value: GHS(totals.totalCash) },
          { label: "MOMO",        value: GHS(totals.totalMomo) },
          { label: "BANK",        value: GHS(totals.totalBank) },
        ].map(({ label, value }) => (
          <div key={label} className="px-3 py-2 border-r border-gray-200 last:border-r-0">
            <p className="text-gray-400 text-[8px] font-black tracking-widest">{label}</p>
            <p className="font-black text-[11px] text-[#1d6f42] mt-0.5">{value}</p>
          </div>
        ))}
      </div>

      {/* Grid */}
      <div className="overflow-auto max-h-44">
        <table className="w-full border-collapse">
          <thead>
            <tr className="bg-[#1d6f42]">
              <th className="w-8 px-2 py-1.5 text-white/60 text-[9px] font-normal border-r border-white/10">#</th>
              {cols.map(c => (
                <th key={c} className="px-2 py-1.5 text-left text-[9px] font-black text-white border-r border-white/10 last:border-r-0 whitespace-nowrap">{c}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filtered.length === 0 ? (
              <tr><td colSpan={cols.length + 1} className="text-center text-gray-400 py-5">No data</td></tr>
            ) : filtered.map((r, i) => (
              <tr key={r.id} className={i % 2 === 0 ? "bg-white" : "bg-[#f0faf5]/60"}>
                <td className="px-2 py-1.5 text-gray-300 text-center border-r border-gray-100">{i + 1}</td>
                <td className="px-2 py-1.5 font-bold border-r border-gray-100">{r.branch}</td>
                <td className="px-2 py-1.5 text-gray-500 border-r border-gray-100">{r.date}</td>
                <td className="px-2 py-1.5 border-r border-gray-100">
                  <span className="bg-emerald-100 text-emerald-700 px-1.5 py-0.5 rounded font-bold text-[8px]">{r.status}</span>
                </td>
                <td className="px-2 py-1.5 font-black border-r border-gray-100">{GHS(r.total)}</td>
                <td className="px-2 py-1.5 text-[#059669] font-bold border-r border-gray-100">{GHS(r.cash)}</td>
                <td className="px-2 py-1.5 text-[#2563eb] font-bold border-r border-gray-100">{GHS(r.momo)}</td>
                <td className="px-2 py-1.5 text-[#4f46e5] font-bold border-r border-gray-100">{GHS(r.bank)}</td>
                <td className="px-2 py-1.5 text-[#dc2626] font-bold border-r border-gray-100">{GHS(r.credit)}</td>
                <td className="px-2 py-1.5 text-[#7c3aed] font-bold border-r border-gray-100">{GHS(r.profit)}</td>
                <td className="px-2 py-1.5 text-gray-400">{pct(r.profit, r.total)}%</td>
              </tr>
            ))}
            {/* Totals row */}
            {filtered.length > 0 && (
              <tr className="bg-[#1d6f42]/5 border-t-2 border-[#1d6f42]/20 font-black">
                <td className="px-2 py-1.5 border-r border-gray-100" />
                <td className="px-2 py-1.5 border-r border-gray-100 text-[#1d6f42]">TOTAL</td>
                <td className="px-2 py-1.5 border-r border-gray-100" />
                <td className="px-2 py-1.5 border-r border-gray-100" />
                <td className="px-2 py-1.5 border-r border-gray-100">{GHS(filtered.reduce((s,r)=>s+r.total,0))}</td>
                <td className="px-2 py-1.5 border-r border-gray-100 text-[#059669]">{GHS(filtered.reduce((s,r)=>s+r.cash,0))}</td>
                <td className="px-2 py-1.5 border-r border-gray-100 text-[#2563eb]">{GHS(filtered.reduce((s,r)=>s+r.momo,0))}</td>
                <td className="px-2 py-1.5 border-r border-gray-100 text-[#4f46e5]">{GHS(filtered.reduce((s,r)=>s+r.bank,0))}</td>
                <td className="px-2 py-1.5 border-r border-gray-100 text-[#dc2626]">{GHS(filtered.reduce((s,r)=>s+r.credit,0))}</td>
                <td className="px-2 py-1.5 border-r border-gray-100 text-[#7c3aed]">{GHS(filtered.reduce((s,r)=>s+r.profit,0))}</td>
                <td className="px-2 py-1.5" />
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

/* ── Export Modal ── */
function ExportModal({ type, onClose, totals, filtered, period, branchFilter }: {
  type: ExportType;
  onClose: () => void;
  totals: any;
  filtered: any[];
  period: string;
  branchFilter: string;
}) {
  const [done, setDone] = useState(false);

  function handleExport() {
    setDone(true);
    setTimeout(onClose, 2200);
  }

  const isPdf = type === "pdf";
  const filename = isPdf
    ? `BranchControl_Report_${period.replace(/\s+/g, "_")}.pdf`
    : `BranchControl_Report_${period.replace(/\s+/g, "_")}.xlsx`;

  return (
    <AnimatePresence>
      {type && (
        <motion.div
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          onClick={onClose}
        >
          <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" />
          <motion.div
            initial={{ opacity: 0, y: 40, scale: 0.96 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 40, scale: 0.96 }}
            transition={{ type: "spring", bounce: 0.18 }}
            onClick={e => e.stopPropagation()}
            className="relative z-10 w-full max-w-2xl bg-card rounded-3xl border border-border shadow-2xl overflow-hidden"
          >
            {/* Modal header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-border">
              <div className="flex items-center gap-3">
                <div className={`h-9 w-9 rounded-xl flex items-center justify-center ${isPdf ? "bg-red-100 dark:bg-red-900/30" : "bg-emerald-100 dark:bg-emerald-900/30"}`}>
                  {isPdf ? <FileText className={`h-4 w-4 text-red-600`} /> : <Table2 className="h-4 w-4 text-emerald-600" />}
                </div>
                <div>
                  <p className="font-black text-foreground text-sm">{isPdf ? "PDF Report Preview" : "Excel Spreadsheet Preview"}</p>
                  <p className="text-xs text-muted-foreground">{filename}</p>
                </div>
              </div>
              <button onClick={onClose} className="rounded-xl bg-muted p-2 hover:bg-muted/70 transition-colors">
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* Preview area */}
            <AnimatePresence mode="wait">
              {done ? (
                <motion.div
                  key="done"
                  initial={{ opacity: 0, scale: 0.85 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="flex flex-col items-center py-14"
                >
                  <div className="h-16 w-16 rounded-full bg-emerald-100 dark:bg-emerald-900/40 flex items-center justify-center mb-4">
                    <CheckCircle2 className="h-8 w-8 text-emerald-600" />
                  </div>
                  <p className="text-lg font-black text-foreground">Export Ready</p>
                  <p className="text-sm text-muted-foreground mt-1">{filename}</p>
                  <p className="text-xs text-muted-foreground/50 mt-3">Your file has been prepared for download.</p>
                </motion.div>
              ) : (
                <motion.div key="preview" className="p-4">
                  {/* Rendered preview */}
                  <div className="mb-4">
                    <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground mb-2 px-1">Document Preview</p>
                    {isPdf
                      ? <PdfPreview totals={totals} filtered={filtered} period={period} branchFilter={branchFilter} />
                      : <ExcelPreview totals={totals} filtered={filtered} period={period} branchFilter={branchFilter} />
                    }
                  </div>

                  {/* Meta info */}
                  <div className="flex items-center gap-4 px-1 mb-4 text-xs text-muted-foreground">
                    <span><strong className="text-foreground">{filtered.length}</strong> report{filtered.length !== 1 ? "s" : ""}</span>
                    <span>·</span>
                    <span>Period: <strong className="text-foreground">{period}</strong></span>
                    <span>·</span>
                    <span>{branchFilter === "All" ? "All Branches" : branchFilter}</span>
                  </div>

                  {/* Download button */}
                  <button
                    onClick={handleExport}
                    className={`w-full flex items-center justify-center gap-2 rounded-2xl py-3.5 text-sm font-black text-white transition-all hover:opacity-90 ${isPdf ? "bg-red-600" : "bg-[#1d6f42]"}`}
                  >
                    <Download className="h-4 w-4" />
                    Download {isPdf ? "PDF" : "Excel"}
                  </button>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

export default function Reports() {
  const [period, setPeriod] = useState("Today");
  const [branchFilter, setBranchFilter] = useState("All");
  const [exportModal, setExportModal] = useState<ExportType>(null);
  const { data: reports, isLoading: reportsLoading } = useListReports();
  const { data: summary, isLoading: summaryLoading } = useGetReportsSummary();

  const totals = summary ?? { totalSales: 0, totalProfit: 0, totalCash: 0, totalMomo: 0, totalBank: 0, totalCredit: 0, totalItems: 0, marginPct: 0 };
  const filtered = (reports ?? []).filter(r => branchFilter === "All" || r.branch === branchFilter);
  const grandTotal = filtered.reduce((s, r) => s + r.total, 0);

  return (
    <div className="p-6 space-y-6 max-w-5xl" data-testid="page-reports">
      <ExportModal
        type={exportModal}
        onClose={() => setExportModal(null)}
        totals={totals}
        filtered={filtered}
        period={period}
        branchFilter={branchFilter}
      />

      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <h1 className="text-2xl font-black text-foreground">Reports</h1>
        <div className="flex gap-2 flex-wrap">
          {PERIODS.map(p => (
            <button
              key={p}
              data-testid={`period-${p.toLowerCase().replace(/\s+/g, "-")}`}
              onClick={() => setPeriod(p)}
              className={`rounded-xl px-4 py-2 text-sm font-bold transition-all ${period === p ? "bg-primary text-primary-foreground shadow-lg" : "bg-card border border-border text-muted-foreground hover:border-foreground/30"}`}
            >
              {p}
            </button>
          ))}
        </div>
      </div>

      {/* Summary */}
      <div className="rounded-2xl border-l-4 border-l-primary border border-border bg-card shadow-sm p-7">
        <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">{period} Summary — All Branches</p>
        {summaryLoading ? (
          <Skeleton className="h-14 w-48 mt-3 rounded-xl" />
        ) : (
          <h2 className="mt-3 text-5xl font-black text-foreground" data-testid="summary-total">{GHS(totals.totalSales)}</h2>
        )}
        <p className="text-muted-foreground mt-1">{totals.totalItems} items sold</p>

        <div className="mt-6 pt-5 border-t border-border grid grid-cols-2 gap-3 md:grid-cols-6">
          {[
            { label: "Cash",   value: GHS(totals.totalCash),   color: "text-emerald-600" },
            { label: "MoMo",   value: GHS(totals.totalMomo),   color: "text-blue-600" },
            { label: "Bank",   value: GHS(totals.totalBank),   color: "text-indigo-600" },
            { label: "Credit", value: GHS(totals.totalCredit), color: "text-red-600" },
            { label: "Profit", value: GHS(totals.totalProfit), color: "text-purple-600" },
            { label: "Margin", value: `${totals.marginPct}%`,  color: "text-amber-600" },
          ].map(({ label, value, color }) => (
            <div key={label} className="rounded-xl bg-muted/50 p-4">
              <p className="text-xs font-black uppercase tracking-widest text-muted-foreground">{label}</p>
              <p className={`mt-1.5 text-xl font-black ${color}`} data-testid={`summary-${label.toLowerCase()}`}>
                {summaryLoading ? "..." : value}
              </p>
            </div>
          ))}
        </div>

        {/* Export buttons only */}
        <div className="mt-5 flex flex-wrap gap-2">
          <button
            data-testid="button-export-pdf"
            onClick={() => setExportModal("pdf")}
            className="flex items-center gap-2 rounded-xl bg-muted px-4 py-2 text-sm font-bold text-foreground hover:bg-muted/70 transition-all"
          >
            <FileText className="h-3.5 w-3.5 text-red-500" />
            Export PDF
          </button>
          <button
            data-testid="button-excel"
            onClick={() => setExportModal("excel")}
            className="flex items-center gap-2 rounded-xl bg-muted px-4 py-2 text-sm font-bold text-foreground hover:bg-muted/70 transition-all"
          >
            <Table2 className="h-3.5 w-3.5 text-emerald-500" />
            Excel
          </button>
        </div>
      </div>

      {/* Branch filter + grand total */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex gap-2 flex-wrap">
          <span className="text-xs font-black uppercase tracking-widest text-muted-foreground self-center">Filter</span>
          {BRANCH_FILTERS.map(b => (
            <button key={b} onClick={() => setBranchFilter(b)}
              className={`rounded-xl px-4 py-2 text-sm font-bold transition-all ${branchFilter === b ? "bg-primary text-primary-foreground" : "bg-card border border-border text-muted-foreground hover:border-foreground/30"}`}>
              {b}
            </button>
          ))}
        </div>
        {filtered.length > 0 && (
          <div className="text-right">
            <p className="text-xs font-bold text-muted-foreground">Showing {filtered.length} report{filtered.length !== 1 ? "s" : ""}</p>
            <p className="text-xl font-black text-foreground">{GHS(grandTotal)} total</p>
          </div>
        )}
      </div>

      {/* Reports list */}
      {reportsLoading ? (
        <div className="space-y-3">
          {[1, 2, 3].map(i => <Skeleton key={i} className="h-36 w-full rounded-2xl" />)}
        </div>
      ) : filtered.length === 0 ? (
        <div className="rounded-2xl border border-border bg-card p-12 text-center">
          <p className="text-muted-foreground">No reports yet. Use Enter Book to start recording sales.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map(r => (
            <div key={r.id} className="rounded-2xl border border-border bg-card shadow-sm p-5" data-testid={`card-report-${r.id}`}>
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap mb-1">
                    <p className="font-black text-foreground text-lg">{r.branch}</p>
                    <span className="text-xs bg-muted text-muted-foreground px-2 py-0.5 rounded-full font-bold">{r.date}</span>
                    <span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full font-bold">{r.status}</span>
                  </div>
                  <p className="text-3xl font-black text-foreground" data-testid={`report-total-${r.id}`}>{GHS(r.total)}</p>
                  <p className="text-sm text-muted-foreground mt-0.5">{r.itemsSold} items sold</p>
                </div>
                <div className="text-right text-sm space-y-1 shrink-0">
                  <div className="flex gap-2 justify-end">
                    <span className="text-xs font-bold text-muted-foreground">Cash</span>
                    <span className="font-black text-emerald-600">{GHS(r.cash)}</span>
                  </div>
                  <div className="flex gap-2 justify-end">
                    <span className="text-xs font-bold text-muted-foreground">MoMo</span>
                    <span className="font-black text-blue-600">{GHS(r.momo)}</span>
                  </div>
                  {r.bank > 0 && (
                    <div className="flex gap-2 justify-end">
                      <span className="text-xs font-bold text-muted-foreground">Bank</span>
                      <span className="font-black text-indigo-600">{GHS(r.bank)}</span>
                    </div>
                  )}
                  <div className="flex gap-2 justify-end">
                    <span className="text-xs font-bold text-muted-foreground">Credit</span>
                    <span className="font-black text-red-600">{GHS(r.credit)}</span>
                  </div>
                  <div className="flex gap-2 justify-end">
                    <span className="text-xs font-bold text-muted-foreground">Profit</span>
                    <span className="font-black text-purple-600">{GHS(r.profit)}</span>
                  </div>
                </div>
              </div>
              <div className="mt-4 pt-3 border-t border-border">
                <div className="h-2 rounded-full bg-muted overflow-hidden">
                  <div className="h-full rounded-full bg-purple-500 transition-all" style={{ width: `${Math.min(100, pct(r.profit, r.total))}%` }} />
                </div>
                <p className="text-xs text-muted-foreground mt-1">{pct(r.profit, r.total)}% profit margin</p>
              </div>
            </div>
          ))}

        </div>
      )}
    </div>
  );
}
